### ISSUE TITLE
Forc plugin compatibility, e.g. `forc-debugger`

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-debugger#15]
Should we consider renaming this repo to `forc-debugger`? This would allow the debugger to be run as a forc plugin once installed.

cc @adlerjohn @mitchmindtree

**Comment by mitchmindtree** [comment]
Yeah I think that makes sense :thinking:

I can imagine a future we might want to support debugging FVM bytecode that was generated from some means other than the Sway compiler in which case you wouldn't particularly want to use the debugger via `forc` as it has the whole Sway package graph built in. That said, the user can always just use `forc-debugger` directly in those cases without `forc` itself.

If we want to allow the debugger to keep an independent name, we can always add a small CLI wrapper downstream as an alternative approach too.

**Comment by mitchmindtree** [comment]
How about the following:

1. Implement `fuel-debugger` independently within this repo. It acts purely as a standalone FVM client, accepts all configuration via CLI args and has no awareness of Sway or `forc` in particular.

2. Create a `forc-debugger` (or `forc-dbg`?) wrapper command at the sway repo within the `plugins` directory. Extends the debugger with any sway/forc-specific functionality, such as configuration via manifest, ensuring the project is built before debugging begins, etc. Has documentation auto-generated along with the rest of the sway repo's `plugins/` directory.

Perhaps this is a nice separation of concerns, where yourself, @Dentosal and client team can continue to take care of `fuel-debugger`, while the Sway Tooling team takes care of the downstream `forc` wrapper?

**Comment by mitchmindtree** [comment]
I've opened a tracking issue for a downstream `forc` debugger command here: https://github.com/FuelLabs/sway/issues/2350

**Comment by sdankel** [comment]
We'll need to do some maintenance on this repo before it can be used in forc. Related https://github.com/FuelLabs/fuel-debugger/pull/16

**Comment by sdankel** [comment]
We've decided to move this code into the Sway repo since the debugger will depend on the same code as forc-test, forc-submit, and SourceMaps within the compiler. It'll be easier to manage as a forc plugin within that repo (consistent releases, version bumps, etc)
